# <font color="maroon"><h4 align="center">Pandas Concat and Merge: Exercise</h4></font>

In [2]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the 3 csv files provided into seperate dataframes (movies.csv to df_movies, financials.csv to df_financials, languages.csv to df_languages).
- show the top 3 rows for each dataframe.

In [3]:
#for movies.csv
import pandas as pd
df1=pd.read_csv("movies.csv")

#for financials.csv
df2=pd.read_csv("financials.csv")
#for languages.csv
df3=pd.read_csv("languages.csv")

In [4]:
#show top3 rows in df_movies
top3=df1.head(3)
top3

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5

In [5]:
#show top3 rows in df_financials

In [6]:
#show top3 rows in df_languages

### <font color="purple">**Question2**</font>
- Read the csv file 'new_movies.csv' and store it into dataframe 'df_new_movies'
- Now, concat the dataframes [df_movies, df_new_movies] and store the results again to df_movies. Make sure to ignore the index while concatenating

In [7]:
#read the csv file: 'new_movies.csv'
import pandas as pd
df_new=pd.read_csv("new_movies.csv")

#show the dataframe
df_new

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1
1,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
2,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5

In [8]:
#concat the two dataframes ['df_movies', df_new_movies]
df1=pd.concat([df1,df_new],ignore_index=True)
#show the last 5 rows
df1.tail()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1
39,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1
40,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
41,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5

### <font color="purple">**Question3**</font>

- Merge the dataframe df_movies with the df_languages on 'language_id'.
- Make sure you perform a **inner** join here.
- Store the result again to df_movies

In [9]:
#perform the join operation


#show the top 5 rows

### <font color="purple">**Question4**</font>

- Merge the dataframe df_movies with the df_financials on 'movie_id'.
- Make sure you perform a **left** join here.
- Store the result again to df_movies

In [10]:
#perform the join operation


#show the last 5 rows

### <font color="purple">**Question5**</font>

- Save the 'df_movies' dataframe with name 'final_complete_data.csv'.
- Only take the columns 'movie_id', 'title', 'lang_name', 'budget', 'revenue', 'currency'
- set the index to False while saving the dataframe

In [11]:
#save the dataframe to 'final_complete_data.csv'